# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'ModarebAraby' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ModarebAraby
  target 'ModarebAraby-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'



    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  end

  target 'ModarebArabyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ModarebAraby-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ModarebAraby-tvOS

  # target 'ModarebAraby-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end
